version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_URL_DIRIGIR_EN_LOGIN_ADMIN=${NEXT_PUBLIC_URL_DIRIGIR_EN_LOGIN_ADMIN}
        - NEXT_PUBLIC_URL_DIRIGIR_EN_LOGIN_ASISTENTE=${NEXT_PUBLIC_URL_DIRIGIR_EN_LOGIN_ASISTENTE}
    ports:
      - 3102:3007
